import {randomBytes,createHmac,timingSafeEqual} from 'node:crypto';
const identifier=prefix=>prefix+randomBytes(12).toString('hex');
const fail=(message,status=400)=>Object.assign(new Error(message),{status});
const money=n=>Number.isSafeInteger(n)&&n>=0;
export function createCommerce({service,provider,keyId,keySecret,now=Date.now,productPrices={},productNames={},shippingPaise=null,boxPaise=null}){
 const db=service.db;db.exec(`
 CREATE TABLE IF NOT EXISTS gifts(id TEXT PRIMARY KEY,owner TEXT NOT NULL,status TEXT NOT NULL,data TEXT NOT NULL,payment TEXT UNIQUE);
 CREATE TABLE IF NOT EXISTS payment_orders(id TEXT PRIMARY KEY,target TEXT NOT NULL,kind TEXT NOT NULL,owner TEXT NOT NULL,amount INTEGER NOT NULL,state TEXT NOT NULL,provider_order TEXT UNIQUE,payment TEXT UNIQUE,error TEXT,created INTEGER NOT NULL);
 CREATE UNIQUE INDEX IF NOT EXISTS payment_target_active ON payment_orders(kind,target) WHERE state IN ('creating','unknown','ready','paid');
 CREATE TABLE IF NOT EXISTS payment_events(id TEXT PRIMARY KEY,at INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS payment_refunds(id TEXT PRIMARY KEY,payment TEXT NOT NULL,amount INTEGER NOT NULL,status TEXT NOT NULL);
 `);
 const columns=db.prepare('PRAGMA table_info(payment_orders)').all().map(c=>c.name);for(const column of ['checked','refund_checked'])if(!columns.includes(column))db.exec('ALTER TABLE payment_orders ADD COLUMN '+column+' INTEGER NOT NULL DEFAULT 0');
 const one=(q,...p)=>db.prepare(q).get(...p),all=(q,...p)=>db.prepare(q).all(...p),run=(q,...p)=>db.prepare(q).run(...p);
 const audit=(u,action,record)=>run('INSERT INTO audit(at,actor,action,record) VALUES(?,?,?,?)',now(),u.phone,action,record);
 const gift=g=>({...JSON.parse(g.data),id:g.id,status:g.status,paymentId:g.payment});
 function ownGift(u,id){const g=one('SELECT * FROM gifts WHERE id=?',id);if(!g||(g.owner!==u.phone&&u.role!=='admin'))throw fail('Gift order not found.',404);return g;}
 function listGifts(u){return all(u.role==='admin'?'SELECT * FROM gifts ORDER BY rowid DESC':'SELECT * FROM gifts WHERE owner=? ORDER BY rowid DESC',...(u.role==='admin'?[]:[u.phone])).map(gift);}
 function createGift(u,input){
  if(!u.name)throw fail('Complete your registration first.');
  const address=String(input.deliveryAddress||'').trim(),city=String(input.city||'').trim(),pin=String(input.pincode||'');
  if(address.length<8||address.length>1000||!city||city.length>120||! /^[1-9]\d{5}$/.test(pin))throw fail('Enter a complete Indian delivery address, city and six-digit PIN.');
  if(!Array.isArray(input.items)||!input.items.length||input.items.length>30)throw fail('Select at least one gift item.');
  const seen=new Set();let subtotal=0,priced=true;
  const items=input.items.map(item=>{const id=String(item.id||''),quantity=Number(item.quantity);if(!Object.hasOwn(productNames,id)||seen.has(id)||!Number.isSafeInteger(quantity)||quantity<1||quantity>20)throw fail('Invalid gift item or quantity.');seen.add(id);const amount=productPrices[id];if(!money(amount)||amount<=0)priced=false;else subtotal+=amount*quantity;return {id,name:productNames[id],quantity,unitAmount:money(amount)&&amount>0?amount:null};});
  const packaging=input.boxPackaging===true,shipping=money(shippingPaise)?shippingPaise:null,box=packaging?(money(boxPaise)?boxPaise:null):0;
  const amount=priced&&shipping!==null&&box!==null?subtotal+shipping+box:null;if(amount!==null&&!money(amount))throw fail('Order total is invalid.');
  const data={customerName:u.name,customerPhone:u.phone,customerEmail:String(input.customerEmail||'').slice(0,200),recipientName:String(input.recipientName||u.name).trim().slice(0,120),giftMessage:String(input.giftMessage||'').slice(0,1000),deliveryAddress:address,city,pincode:pin,items,boxPackaging:packaging,shippingAmount:shipping,boxAmount:box,amount,stockApproved:false,createdAt:new Date(now()).toISOString(),trackingNumber:null};
  const id=identifier('GIFT-');run('INSERT INTO gifts VALUES(?,?,?,?,NULL)',id,u.phone,'requested',JSON.stringify(data));audit(u,'gift_requested',id);return gift(ownGift(u,id));
 }
 function approve(u,kind,id){service.admin(u);if(kind==='booking'){const b=service.own(u,id),d=JSON.parse(b.data);if(b.status!=='requested'||b.start<=now())throw fail('Only a future requested ceremony can be approved.');if(one('SELECT id FROM payment_orders WHERE target=? AND kind=?',id,kind))throw fail('A payment order exists; contact support before changing its quote.');const configured=service.priceFor(d.packageId);if(!money(configured)||configured<=0)throw fail('Set the final server-side package price first.');d.amount=configured;d.totalPrice=configured/100;d.availabilityApproved=true;d.approvedAt=new Date(now()).toISOString();run('UPDATE bookings SET data=? WHERE id=?',JSON.stringify(d),id);audit(u,'availability_approved',id);return service.unpack(service.own(u,id));}
  const g=ownGift(u,id),d=JSON.parse(g.data);if(g.status!=='requested')throw fail('Only a requested gift can be approved.');if(one('SELECT id FROM payment_orders WHERE target=? AND kind=?',id,kind))throw fail('A payment order exists; its quote cannot be changed.');let amount=0;for(const item of d.items){const price=productPrices[item.id];if(!money(price)||price<=0)throw fail('Set final server-side gift prices first.');item.unitAmount=price;amount+=price*item.quantity;}if(!money(shippingPaise)||d.boxPackaging&&!money(boxPaise))throw fail('Set shipping and packaging charges explicitly, including zero for free shipping.');d.shippingAmount=shippingPaise;d.boxAmount=d.boxPackaging?boxPaise:0;d.amount=amount+d.shippingAmount+d.boxAmount;if(!money(d.amount)||d.amount<=0)throw fail('Invalid final gift quote.');d.stockApproved=true;d.approvedAt=new Date(now()).toISOString();run('UPDATE gifts SET data=? WHERE id=?',JSON.stringify(d),id);audit(u,'gift_stock_and_coverage_approved',id);return gift(ownGift(u,id));
 }
 function target(u,kind,id){if(kind==='booking'){const b=service.own(u,id);if(b.owner!==u.phone&&u.role!=='admin')throw fail('Booking not found.',404);return {row:b,data:JSON.parse(b.data)};}if(kind==='gift'){const g=ownGift(u,id);return {row:g,data:JSON.parse(g.data)};}throw fail('Invalid order type.');}
 const publicOrder=o=>({ok:true,orderId:o.provider_order,amount:o.amount,currency:'INR',keyId,targetId:o.target,kind:o.kind,state:o.state});
 async function resolveUnknown(u,localId,input){service.admin(u);const o=one('SELECT * FROM payment_orders WHERE id=?',localId);if(!o||!['unknown','creating'].includes(o.state))throw fail('This order does not need recovery.');const p=await provider.order(String(input.orderId||''));if(p.amount!==o.amount||p.currency!=='INR'||p.receipt!==o.id||p.notes?.target_id!==o.target)throw fail('Provider order does not match the recorded receipt and quote.');run('UPDATE payment_orders SET provider_order=?,state=?,error=NULL WHERE id=?',p.id,'ready',o.id);audit(u,'payment_order_recovered',o.target);return {ok:true};}
 async function order(u,input){const kind=input.kind||'booking',id=String(input.targetId||input.bookingId||''),{row,data}=target(u,kind,id);
  if(row.status!=='requested')throw fail('This order is no longer awaiting payment.');
  if(kind==='booking'&&row.start<=now())throw fail('Ceremony time has elapsed. Contact support.');
  if(!(kind==='booking'?data.availabilityApproved:data.stockApproved))throw fail('Your request must be approved for availability/stock and delivery before payment.');
  if(!money(data.amount)||data.amount<=0)throw fail('The final price is not configured yet.');if(!keyId||!keySecret)throw fail('Payment configuration is unavailable.',503);
  const existing=one('SELECT * FROM payment_orders WHERE kind=? AND target=? AND state IN (?,?,?,?)',kind,id,'creating','unknown','ready','paid');
  if(existing){if(existing.state!=='ready')throw fail('Payment creation or verification is pending. Contact support before retrying.',409);return publicOrder(existing);}
  const localId=identifier('PO-');run('INSERT INTO payment_orders(id,target,kind,owner,amount,state,created) VALUES(?,?,?,?,?,?,?)',localId,id,kind,row.owner,data.amount,'creating',now());
  try{const p=await provider.createOrder({amount:data.amount,currency:'INR',receipt:localId,notes:{target_id:id,target_kind:kind,booking_id:kind==='booking'?id:''}});if(!/^order_[A-Za-z0-9]+$/.test(p.id)||p.amount!==data.amount||p.currency!=='INR')throw Object.assign(new Error('Invalid provider order'),{ambiguous:true});run('UPDATE payment_orders SET state=?,provider_order=? WHERE id=?','ready',p.id,localId);audit(u,'payment_order_created',id);return publicOrder(one('SELECT * FROM payment_orders WHERE id=?',localId));}
  catch(e){run('UPDATE payment_orders SET state=?,error=? WHERE id=?',e.ambiguous?'unknown':'failed','Provider order creation failed; review provider before retry.',localId);throw fail('Could not create payment order. Please contact support if the issue continues.',503);}
 }
 function signature(orderId,paymentId,sig){const expected=createHmac('sha256',keySecret).update(orderId+'|'+paymentId).digest('hex');return /^[a-f0-9]{64}$/i.test(String(sig||''))&&timingSafeEqual(Buffer.from(expected,'hex'),Buffer.from(sig,'hex'));}
 function applyCapture(o,p){if(p.id!==o.payment&&o.state==='paid')throw fail('This order has already been paid.');if(p.status!=='captured'||p.currency!=='INR'||p.amount!==o.amount||p.order_id!==o.provider_order)throw fail('Payment is not captured or does not match the recorded order.');
  const reused=one('SELECT id FROM payment_orders WHERE payment=? AND id<>?',p.id,o.id);if(reused)throw fail('Payment already belongs to another order.');if(o.state==='paid')return;
  db.exec('BEGIN IMMEDIATE');try{const current=one('SELECT * FROM payment_orders WHERE id=?',o.id);if(current.state==='paid'){if(current.payment!==p.id)throw fail('This order already has a different captured payment; contact support.');db.exec('COMMIT');return;}
   if(o.kind==='gift'){const g=one('SELECT * FROM gifts WHERE id=?',o.target);if(g.status!=='requested')throw fail('Gift state changed; payment requires staff review.');run('UPDATE gifts SET status=?,payment=? WHERE id=?','paid',p.id,g.id);const d=JSON.parse(g.data);service.queueGiftNotification('mantrakshata_gift_order_confirmed',g.id,g.owner,[d.customerName,g.id,d.recipientName,(o.amount/100).toFixed(2)]);}
   run('UPDATE payment_orders SET state=?,payment=?,error=NULL WHERE id=?','paid',p.id,o.id);audit({phone:o.owner},'payment_captured',o.target);db.exec('COMMIT');
  }catch(e){db.exec('ROLLBACK');throw e;}
 }
 async function finishBooking(o,p){if(o.kind!=='booking')return;const staff={phone:'payment-service',role:'admin'},b=service.own(staff,o.target);if(b.status==='requested'&&b.start<=now()){run('UPDATE payment_orders SET error=? WHERE id=?','Captured after ceremony time; staff must reconcile refund.',o.id);return;}if(b.status==='requested')await service.confirm(staff,o.target,{paymentId:p.id},{...p,notes:{...p.notes,booking_id:o.target}});else if(b.status==='cancelled')run('UPDATE payment_orders SET error=? WHERE id=?','Captured after cancellation; staff must reconcile refund.',o.id);}
 async function verify(u,input){const orderId=String(input.razorpay_order_id||''),paymentId=String(input.razorpay_payment_id||''),o=one('SELECT * FROM payment_orders WHERE provider_order=?',orderId);if(!o||(o.owner!==u.phone&&u.role!=='admin'))throw fail('Payment order not found.',404);if(!/^pay_[A-Za-z0-9]+$/.test(paymentId)||!signature(o.provider_order,paymentId,input.razorpay_signature))throw fail('Invalid payment signature.');const p=await provider.payment(paymentId);applyCapture(o,p);await finishBooking(o,p);return {ok:true,verified:true,paymentId:p.id,orderId:o.provider_order,targetId:o.target,status:one(o.kind==='booking'?'SELECT status FROM bookings WHERE id=?':'SELECT status FROM gifts WHERE id=?',o.target).status};}
 function recordRefund(r,o){if(!r.id||r.payment_id!==o.payment||!money(r.amount)||r.amount<=0||r.amount>o.amount||!['pending','processed','failed'].includes(r.status))throw fail('Invalid provider refund.');const previous=one('SELECT status FROM payment_refunds WHERE id=?',r.id);if(previous?.status!=='processed')run('INSERT OR REPLACE INTO payment_refunds VALUES(?,?,?,?)',r.id,r.payment_id,r.amount,r.status);const total=one('SELECT COALESCE(sum(amount),0) AS n FROM payment_refunds WHERE payment=? AND status=?',o.payment,'processed').n;if(total>=o.amount){run('UPDATE payment_orders SET error=? WHERE id=?','Fully refunded',o.id);if(o.kind==='gift')run('UPDATE gifts SET status=? WHERE id=?','refunded',o.target);else {const b=service.own({role:'admin'},o.target);if(!['cancelled','completed'].includes(b.status))service.change({phone:'payment-service',role:'admin'},o.target,'cancel',{});}}}
 let reconciling=false;
 async function reconcile(){if(reconciling)return;reconciling=true;try{for(const o of all("SELECT * FROM payment_orders WHERE state='ready' OR (state='paid' AND kind='booking' AND target IN (SELECT id FROM bookings WHERE status='requested')) ORDER BY checked ASC LIMIT 20")){run('UPDATE payment_orders SET checked=? WHERE id=?',now(),o.id);try{const payments=await provider.orderPayments(o.provider_order);const p=payments.items?.find(p=>p.status==='captured');if(p){applyCapture(o,p);await finishBooking(o,p);}}catch{run('UPDATE payment_orders SET error=? WHERE id=?','Reconciliation pending; retry or inspect provider.',o.id);}}if(provider.paymentRefunds)for(const o of all("SELECT * FROM payment_orders WHERE state='paid' AND (error IS NULL OR error<>'Fully refunded') ORDER BY refund_checked ASC LIMIT 20")){run('UPDATE payment_orders SET refund_checked=? WHERE id=?',now(),o.id);try{for(const r of (await provider.paymentRefunds(o.payment)).items||[])recordRefund(r,o);}catch{/* Recheck on the next pass; never fabricate refund success. */}}}finally{reconciling=false;}}
 async function webhook(event,eventId){if(!eventId||eventId.length>200)throw fail('Missing payment event ID.');if(one('SELECT id FROM payment_events WHERE id=?',eventId))return {ok:true};
  if(['payment.captured','order.paid'].includes(event.event)){const entity=event.payload?.payment?.entity;if(!entity?.id)throw fail('Missing payment entity.');const p=await provider.payment(entity.id),o=one('SELECT * FROM payment_orders WHERE provider_order=?',p.order_id);if(o){applyCapture(o,p);await finishBooking(o,p);}}
  if(['refund.created','refund.processed','refund.failed'].includes(event.event)){const r=event.payload?.refund?.entity;if(r?.id){const actual=await provider.refund(r.id),o=one('SELECT * FROM payment_orders WHERE payment=?',actual.payment_id);if(o){recordRefund(actual,o);audit({phone:'payment-webhook'},'refund_'+actual.status,o.target);}}}
  run('INSERT OR IGNORE INTO payment_events VALUES(?,?)',eventId,now());return {ok:true};
 }
 function fulfil(u,id,input){service.admin(u);const g=ownGift(u,id),d=JSON.parse(g.data),action=String(input.action||'');if(action==='ship'){if(g.status!=='paid'&&g.status!=='packed')throw fail('Only paid or packed gifts can be shipped.');const tracking=String(input.trackingNumber||'').trim().toUpperCase();if(!/^[A-Z]{2}\d{9}IN$/.test(tracking))throw fail('Enter the India Post number: two letters, nine digits and IN.');d.trackingNumber=tracking;d.carrier='India Post';d.shippedAt=new Date(now()).toISOString();}
  else if(action==='pack'){if(g.status!=='paid')throw fail('Only paid gifts can be packed.');}
  else if(action==='deliver'){if(g.status!=='shipped')throw fail('Only a shipped gift can be marked delivered.');d.deliveredAt=new Date(now()).toISOString();}
  else throw fail('Invalid fulfilment action.');const status={ship:'shipped',pack:'packed',deliver:'delivered'}[action];db.exec('BEGIN IMMEDIATE');try{run('UPDATE gifts SET status=?,data=? WHERE id=?',status,JSON.stringify(d),g.id);if(action==='ship')service.queueGiftNotification('mantrakshata_gift_shipped',g.id,g.owner,[d.customerName,g.id,d.recipientName,d.trackingNumber,'https://www.indiapost.gov.in/']);audit(u,'gift_'+status,id);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}return gift(ownGift(u,id));
 }
 function payments(u){service.admin(u);return all('SELECT id,target,kind,amount,state,provider_order,payment,error,created FROM payment_orders ORDER BY created DESC LIMIT 200').map(o=>({...o,refunds:o.payment?all('SELECT * FROM payment_refunds WHERE payment=?',o.payment):[]}));}
 return {createGift,listGifts,ownGift,gift,approve,order,verify,reconcile,webhook,fulfil,payments,resolveUnknown};
}
