import { DatabaseSync } from 'node:sqlite';
import { randomBytes, randomInt, createHmac, timingSafeEqual } from 'node:crypto';
import { mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

export const phone = value => {const n=String(value||'').replace(/\D/g,'');const p=n.length===10?'91'+n:n;return /^91[6-9]\d{9}$/.test(p)?p:'';};
const id=()=>randomBytes(24).toString('hex');
export function createService({database,secret,send,now=Date.now,adminPhones=[],mainPhone='',origin='https://www.mantrakshata.com',prices={},verifyPayment}) {
 if(!secret||secret.length<32)throw new Error('SESSION_SECRET must contain at least 32 characters');
 if(database!==':memory:')mkdirSync(dirname(database),{recursive:true});
 const db=new DatabaseSync(database);db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;
 CREATE TABLE IF NOT EXISTS users(phone TEXT PRIMARY KEY, profile TEXT NOT NULL DEFAULT '{}');
 CREATE TABLE IF NOT EXISTS sessions(hash TEXT PRIMARY KEY,phone TEXT NOT NULL,expires INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS otp(id TEXT PRIMARY KEY,phone TEXT NOT NULL,hash TEXT NOT NULL,expires INTEGER NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,used INTEGER NOT NULL DEFAULT 0);
 CREATE TABLE IF NOT EXISTS limits(key TEXT PRIMARY KEY,start INTEGER NOT NULL,count INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS bookings(id TEXT PRIMARY KEY,owner TEXT NOT NULL,status TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 1,start INTEGER NOT NULL,data TEXT NOT NULL,payment TEXT UNIQUE);
 CREATE TABLE IF NOT EXISTS jobs(id TEXT PRIMARY KEY,booking TEXT,version INTEGER,kind TEXT NOT NULL,recipient TEXT NOT NULL,due INTEGER NOT NULL,deadline INTEGER NOT NULL,state TEXT NOT NULL DEFAULT 'pending',attempts INTEGER NOT NULL DEFAULT 0,payload TEXT,provider_id TEXT,error TEXT);
 CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY,at INTEGER,actor TEXT,action TEXT,record TEXT);
 CREATE TABLE IF NOT EXISTS deliveries(id TEXT PRIMARY KEY,status TEXT,at INTEGER);
 `);
 const run=(q,...p)=>db.prepare(q).run(...p),one=(q,...p)=>db.prepare(q).get(...p),all=(q,...p)=>db.prepare(q).all(...p);
 const hash=v=>createHmac('sha256',secret).update(v).digest('hex');
 const audit=(actor,action,record)=>run('INSERT INTO audit(at,actor,action,record) VALUES(?,?,?,?)',now(),actor,action,record);
 const error=(message,status=400)=>Object.assign(new Error(message),{status});
 const limit=(key,count,ms)=>{const row=one('SELECT * FROM limits WHERE key=?',key);if(!row||row.start+ms<=now()){run('INSERT OR REPLACE INTO limits VALUES(?,?,1)',key,now());return;}if(row.count>=count)throw error('Too many requests. Please try again later.',429);run('UPDATE limits SET count=count+1 WHERE key=?',key);};
 const user=p=>{const row=one('SELECT * FROM users WHERE phone=?',p);const profile=row?JSON.parse(row.profile):{};return {...profile,phone:p,id:hash(p).slice(0,24),isVerified:true,demoVerified:false,role:adminPhones.includes(p)?'admin':'customer',language:profile.language||'English',addresses:profile.addresses||[],notifications:profile.notifications||{whatsapp:true,email:false,reminders:true,marketing:false}};};
 function session(token){const row=one('SELECT * FROM sessions WHERE hash=? AND expires>?',hash(token||''),now());if(!row)throw error('Please sign in to continue.',401);return user(row.phone);}
 function admin(u){if(u.role!=='admin')throw error('Staff access required.',403);}
 function own(u,bookingId){const b=one('SELECT * FROM bookings WHERE id=?',bookingId);if(!b||(u.role!=='admin'&&b.owner!==u.phone))throw error('Booking not found.',404);return b;}
 const unpack=b=>({...JSON.parse(b.data),id:b.id,status:b.status,version:b.version,ceremonyStart:new Date(b.start).toISOString()});
 function queue(jobId,booking,version,kind,recipient,due,deadline,payload=null){if(due<now()||due>=deadline)return;run('INSERT OR IGNORE INTO jobs(id,booking,version,kind,recipient,due,deadline,payload) VALUES(?,?,?,?,?,?,?,?)',jobId,booking,version,kind,recipient,due,deadline,payload?JSON.stringify(payload):null);}
 function reminders(b){for(const [kind,delta] of [['mantrakshata_reminder_1day',86400000],['mantrakshata_reminder_2hours',7200000]])queue(`${b.id}:${b.version}:${kind}`,b.id,b.version,kind,b.owner,b.start-delta,b.start);}
 async function requestOtp(value,ip){const p=phone(value);if(!p)throw error('Enter a valid Indian mobile number.');limit('ip:'+hash(ip),20,3600000);limit('phone-hour:'+p,5,3600000);limit('phone-minute:'+p,1,60000);const challenge=id(),code=String(randomInt(100000,1000000));run('UPDATE otp SET used=1 WHERE phone=?',p);run('INSERT INTO otp(id,phone,hash,expires) VALUES(?,?,?,?)',challenge,p,hash(challenge+':'+code),now()+600000);try{await send(p,'hav_otp1',[code,'Verification','10 mins','918296925577'],code);}catch{run('UPDATE otp SET used=1 WHERE id=?',challenge);throw error('We could not send the verification code. Please try again later.',503);}return {challengeId:challenge,expiresIn:600};}
 function verifyOtp(challenge,code,ip){limit('verify:'+hash(ip),50,3600000);const c=one('SELECT * FROM otp WHERE id=?',String(challenge||''));if(!c||c.used||c.expires<=now()||c.attempts>=5)throw error('Code expired or unavailable. Request another code.');run('UPDATE otp SET attempts=attempts+1 WHERE id=?',c.id);const candidate=hash(c.id+':'+String(code||''));if(!timingSafeEqual(Buffer.from(candidate),Buffer.from(c.hash)))throw error('Incorrect verification code.');run('UPDATE otp SET used=1 WHERE id=?',c.id);run('INSERT OR IGNORE INTO users(phone) VALUES(?)',c.phone);const token=id();run('INSERT INTO sessions VALUES(?,?,?)',hash(token),c.phone,now()+86400000);audit(c.phone,'login','session');return {token,user:user(c.phone)};}
 function saveProfile(u,input){const name=String(input.name||'').trim();if(!name||name.length>120)throw error('Enter your full name.');const previous=user(u.phone);const profile={name,email:String(input.email||'').slice(0,200),language:'English',notifications:{whatsapp:true,email:false,reminders:true,marketing:input.marketing===true}};run('UPDATE users SET profile=? WHERE phone=?',JSON.stringify(profile),u.phone);if(!previous.name&&profile.notifications.marketing)queue('welcome:'+hash(u.phone),null,null,'mantrakshata_welcome_catalog',u.phone,now(),now()+86400000,[name]);return user(u.phone);}
 function startTime(input){const value=String(input.ceremonyStart||'');if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:00\+05:30$/.test(value))throw error('Select a ceremony start time in India.');const t=Date.parse(value);if(!Number.isFinite(t)||t<now()+48*3600000)throw error('Please allow at least 48 hours before the ceremony.');return t;}
 function createBooking(u,input){const start=startTime(input);const name=String(input.name||'').trim(),address=String(input.address||'').trim(),pin=String(input.pincode||'');if(!name||name.length>120||address.length<8||!/^560\d{3}$/.test(pin))throw error('Enter celebrant name and a Bengaluru address with a valid PIN.');if(!/^\d{4}-\d{2}-\d{2}$/.test(input.dob||'')||Date.parse(input.dob)>now())throw error('Enter a valid date of birth.');const packageId=String(input.packageId||'');const amount=Number(prices[packageId]);const data={};for(const k of ['name','dob','birthTime','birthPlace','nakshatra','gotra','rashi','pada','celebrationDate','timeSlot','address','pincode','email','packageId','packageName','occasion','relationship','landmark','mapsLink']){if(input[k]!=null)data[k]=String(input[k]).slice(0,1000);}data.phone=u.phone;data.amount=Number.isSafeInteger(amount)&&amount>0?amount:null;data.bookedAt=new Date(now()).toISOString();data.totalPrice=data.amount?data.amount/100:0;const bookingId='MK-'+id().slice(0,16);run('INSERT INTO bookings(id,owner,status,start,data) VALUES(?,?,?,?,?)',bookingId,u.phone,'requested',start,JSON.stringify(data));audit(u.phone,'booking_requested',bookingId);return unpack(own(u,bookingId));}
 function listBookings(u){return all(u.role==='admin'?'SELECT * FROM bookings ORDER BY start DESC':'SELECT * FROM bookings WHERE owner=? ORDER BY start DESC',...(u.role==='admin'?[]:[u.phone])).map(unpack);}
 async function confirm(u,bookingId,input){admin(u);let b=own(u,bookingId);if(b.status!=='requested')throw error('Only a requested booking can be confirmed.');const d=JSON.parse(b.data);if(!d.amount)throw error('Set a final server-side price and create a new quote before taking payment.');const payment=await verifyPayment(String(input.paymentId||''));if(payment.status!=='captured'||payment.currency!=='INR'||payment.amount!==d.amount||payment.notes?.booking_id!==b.id)throw error('Payment does not match this booking.');db.exec('BEGIN IMMEDIATE');try{b=own(u,bookingId);if(b.status!=='requested')throw error('Booking has already changed.');run('UPDATE bookings SET status=?,payment=? WHERE id=?','confirmed',payment.id,b.id);b=own(u,b.id);queue(b.id+':confirmation',b.id,b.version,'mantrakshata_booking_confirmed',b.owner,now(),b.start);if(mainPhone)queue(b.id+':main',b.id,b.version,'mantrakshata_main_acharya_assignment',mainPhone,now(),b.start);reminders(b);audit(u.phone,'confirmed',b.id);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}return unpack(b);}
 function change(u,bookingId,action,input){admin(u);db.exec('BEGIN IMMEDIATE');try{let b=own(u,bookingId),d=JSON.parse(b.data);if(['cancelled','completed'].includes(b.status))throw error('This booking can no longer be changed.');if(action==='assign'){if(b.status!=='confirmed')throw error('Confirm the booking first.');const p=phone(input.phone);if(!p||!String(input.name||'').trim())throw error('Enter the Pandit name and valid phone.');d.pandit={name:String(input.name).slice(0,120),phone:p,arrival:String(input.arrival||'To be coordinated').slice(0,80)};run('UPDATE jobs SET state=? WHERE booking=? AND state=? AND kind IN (?,?)','cancelled',b.id,'pending','mantrakshata_customer_pandit_details','mantrakshata_pandit_booking_details');d.assignmentVersion=(d.assignmentVersion||0)+1;run('UPDATE bookings SET data=? WHERE id=?',JSON.stringify(d),b.id);for(const [kind,p] of [['mantrakshata_customer_pandit_details',b.owner],['mantrakshata_pandit_booking_details',d.pandit.phone]])queue(`${b.id}:assign:${d.assignmentVersion}:${kind}`,b.id,b.version,kind,p,now(),b.start);}
 else if(action==='cancel'){run('UPDATE bookings SET status=?,version=version+1 WHERE id=?','cancelled',b.id);run('UPDATE jobs SET state=? WHERE booking=? AND state=?','cancelled',b.id,'pending');}
 else if(action==='reschedule'){const start=startTime(input);run('UPDATE jobs SET state=? WHERE booking=? AND state=?','cancelled',b.id,'pending');d.celebrationDate=input.ceremonyStart.slice(0,10);d.timeSlot=input.ceremonyStart.slice(11,16);run('UPDATE bookings SET start=?,version=version+1,data=? WHERE id=?',start,JSON.stringify(d),b.id);b=own(u,b.id);if(b.status==='confirmed')reminders(b);}
 else if(action==='complete'){if(b.status!=='confirmed'||b.start>now())throw error('Only a confirmed ceremony that has started can be completed.');run('UPDATE bookings SET status=? WHERE id=?','completed',b.id);run('UPDATE jobs SET state=? WHERE booking=? AND state=?','cancelled',b.id,'pending');if(user(b.owner).notifications.marketing){const date=new Date(b.start+86400000+19800000).toISOString().slice(0,10);const due=Date.parse(date+'T10:00:00+05:30');queue(b.id+':followup',b.id,b.version,'mantrakshata_next_day_followup',b.owner,Math.max(now(),due),due+86400000);}}
 else throw error('Unknown action.');audit(u.phone,action,b.id);db.exec('COMMIT');return unpack(own(u,b.id));}catch(e){db.exec('ROLLBACK');throw e;}}
 function parameters(job,b){const d=JSON.parse(b.data),customer=user(b.owner).name||d.name,date=new Date(b.start).toLocaleDateString('en-IN',{timeZone:'Asia/Kolkata'}),time=new Date(b.start).toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit'}),venue=d.address+', '+d.pincode,p=d.pandit;switch(job.kind){case 'mantrakshata_booking_confirmed':return [customer,b.id,d.name,d.gotra||'To be confirmed',d.nakshatra||'To be confirmed',date,time,d.packageName,origin+'/dashboard?bookingId='+b.id];case 'mantrakshata_main_acharya_assignment':return ['Main Acharya',b.id,d.name,date,time,d.packageName,venue];case 'mantrakshata_customer_pandit_details':return [customer,b.id,p.name,p.phone,date,time,p.arrival];case 'mantrakshata_pandit_booking_details':return [p.name,b.id,d.name,b.owner,date,time,p.arrival,venue,d.packageName,`Gotra: ${d.gotra||'To be confirmed'}; Nakshatra: ${d.nakshatra||'To be confirmed'}; Rashi: ${d.rashi||'To be confirmed'}`,'None provided'];case 'mantrakshata_reminder_1day':return [customer,d.name,b.id,date,time,venue,'Keep a clean space ready; confirm ritual materials with your coordinator.'];case 'mantrakshata_reminder_2hours':return [customer,d.name,b.id,time,venue];case 'mantrakshata_next_day_followup':return [customer,d.name,b.id];default:throw error('Unsupported lifecycle template');}}
 let working=false;
 async function tick(){if(working)return;working=true;try{run('UPDATE jobs SET state=? WHERE state=?','unknown','sending');run('UPDATE jobs SET state=? WHERE state=? AND deadline<=?','expired','pending',now());for(const job of all('SELECT * FROM jobs WHERE state=? AND due<=? ORDER BY due LIMIT 20','pending',now())){const b=job.booking?one('SELECT * FROM bookings WHERE id=?',job.booking):null;if(job.booking&&(!b||b.version!==job.version||b.status==='cancelled'||(job.kind==='mantrakshata_next_day_followup'?b.status!=='completed':b.status!=='confirmed'))){run('UPDATE jobs SET state=? WHERE id=?','cancelled',job.id);continue;}if(['mantrakshata_welcome_catalog','mantrakshata_next_day_followup'].includes(job.kind)&&!user(job.recipient).notifications.marketing){run('UPDATE jobs SET state=? WHERE id=?','cancelled',job.id);continue;}if(!run('UPDATE jobs SET state=?,attempts=attempts+1 WHERE id=? AND state=?','sending',job.id,'pending').changes)continue;try{const params=job.payload?JSON.parse(job.payload):parameters(job,b);const result=await send(job.recipient,job.kind,params,job.kind==='mantrakshata_main_acharya_assignment'?b.id:undefined);run('UPDATE jobs SET state=?,provider_id=? WHERE id=?','sent',result.id,job.id);}catch(e){const retry=e.safeRetry===true&&job.attempts<4;run('UPDATE jobs SET state=?,due=?,error=? WHERE id=?',retry?'pending':e.ambiguous?'unknown':'failed',now()+60000*Math.pow(2,job.attempts),'Provider dispatch failed; inspect provider status before manual retry.',job.id);}}run('DELETE FROM sessions WHERE expires<?',now());run('DELETE FROM otp WHERE expires<?',now()-86400000);run('DELETE FROM limits WHERE start<?',now()-86400000);}finally{working=false;}}
 return {db,requestOtp,verifyOtp,session,user,saveProfile,createBooking,listBookings,confirm,change,tick,logout(token){run('DELETE FROM sessions WHERE hash=?',hash(token||''));},jobs(u){admin(u);return all('SELECT j.id,j.booking,j.kind,j.due,j.state,j.attempts,j.provider_id,j.error,d.status AS delivery FROM jobs j LEFT JOIN deliveries d ON d.id=j.provider_id ORDER BY j.due DESC LIMIT 200');},retryJob(u,jobId,acknowledgeUnknown){admin(u);const j=one('SELECT * FROM jobs WHERE id=?',jobId);if(!j)throw error('Job not found.',404);if(!['failed','unknown'].includes(j.state)||j.deadline<=now())throw error('This job cannot be retried.');if(j.state==='unknown'&&acknowledgeUnknown!==true)throw error('Check provider delivery first, then acknowledge the duplicate-message risk.');run('UPDATE jobs SET state=?,due=?,attempts=0,error=NULL WHERE id=?','pending',now(),j.id);audit(u.phone,'notification_retry',j.id);return {ok:true};},recordDelivery(messageId,status){if(!['sent','delivered','read','failed'].includes(status))return;run('INSERT OR REPLACE INTO deliveries VALUES(?,?,?)',messageId,status,now());},admin,own,unpack};
}
