export function metaProvider(env,fetcher=fetch){let cache=[],loaded=0;
 const token=env.WHATSAPP_TOKEN,phoneId=env.WHATSAPP_PHONE_NUMBER_ID,waba=env.WHATSAPP_WABA_ID,version=env.META_API_VERSION||'v23.0';
 async function schemas(){if(Date.now()-loaded<300000)return cache;if(!token||!phoneId||!waba)throw new Error('WhatsApp server configuration missing');let url=`https://graph.facebook.com/${version}/${waba}/message_templates?fields=name,status,language,components&limit=100`;const rows=[];for(let page=0;url&&page<10;page++){const res=await fetcher(url,{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(15000)});if(!res.ok)throw new Error('Cannot verify approved WhatsApp templates');const data=await res.json();rows.push(...(data.data||[]));const next=data.paging?.next;url=next&&new URL(next).hostname==='graph.facebook.com'?next:null;}cache=rows;loaded=Date.now();return rows;}
 async function send(to,name,params,button){const templates=await schemas();const candidates=templates.filter(t=>t.name===name&&t.status==='APPROVED');const t=candidates.find(t=>t.language===(env.WHATSAPP_LANGUAGE||'en'))||candidates.find(t=>t.language==='en_US');if(!t)throw new Error('Template is not approved in the configured language');const body=t.components.find(c=>c.type==='BODY');const count=Math.max(0,...[...(body?.text||'').matchAll(/\{\{(\d+)\}\}/g)].map(x=>+x[1]));if(name==='hav_otp1'&&count===1)params=[params[0]];if(count!==params.length||params.some(p=>p===undefined||p===null||String(p).trim()===''))throw new Error('Template parameters do not match the approved template');const components=count?[{type:'body',parameters:params.map(p=>({type:'text',text:String(p)}))}]:[];const buttons=t.components.find(c=>c.type==='BUTTONS')?.buttons||[];for(const [index,b] of buttons.entries()){if(b.type==='URL'&&b.url?.includes('{{1}}')||b.type==='OTP'){if(!button)throw new Error('Template needs a dynamic button value');components.push({type:'button',sub_type:'url',index:String(index),parameters:[{type:'text',text:String(button)}]});}}
 let res;try{res=await fetcher(`https://graph.facebook.com/${version}/${phoneId}/messages`,{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',to,type:'template',template:{name,language:{code:t.language},components}}),signal:AbortSignal.timeout(15000)});}catch{throw Object.assign(new Error('Unknown provider outcome'),{ambiguous:true});}const data=await res.json().catch(()=>({}));if(!res.ok)throw Object.assign(new Error('Provider rejected message'),{safeRetry:res.status===429,ambiguous:res.status>=500});if(!data.messages?.[0]?.id)throw Object.assign(new Error('Missing provider message ID'),{ambiguous:true});return {id:data.messages[0].id};}
 return {send};
}
export async function verifyRazorpayPayment(env,id){if(!/^pay_[A-Za-z0-9]+$/.test(id)||!env.RAZORPAY_KEY_ID||!env.RAZORPAY_KEY_SECRET)throw new Error('Payment verification not configured');const res=await fetch('https://api.razorpay.com/v1/payments/'+id,{headers:{Authorization:'Basic '+Buffer.from(env.RAZORPAY_KEY_ID+':'+env.RAZORPAY_KEY_SECRET).toString('base64')},signal:AbortSignal.timeout(15000)});if(!res.ok)throw new Error('Could not verify payment');return res.json();}

export function razorpayProvider(env,fetcher=fetch){
 async function request(path,body){if(!env.RAZORPAY_KEY_ID||!env.RAZORPAY_KEY_SECRET)throw new Error('Payment configuration missing');let res;try{res=await fetcher('https://api.razorpay.com/v1/'+path,{method:body?'POST':'GET',headers:{Authorization:'Basic '+Buffer.from(env.RAZORPAY_KEY_ID+':'+env.RAZORPAY_KEY_SECRET).toString('base64'),'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000)});}catch{throw Object.assign(new Error('Unknown payment provider result'),{ambiguous:true});}if(!res.ok)throw Object.assign(new Error('Payment provider rejected request'),{ambiguous:res.status>=500});try{return await res.json();}catch{throw Object.assign(new Error('Invalid payment provider response'),{ambiguous:!!body});}}
 const safe=(id,prefix)=>{if(!new RegExp('^'+prefix+'_[A-Za-z0-9]+$').test(id))throw new Error('Invalid provider identifier');return id;};
 return {createOrder:body=>request('orders',body),order:id=>request('orders/'+safe(id,'order')),payment:id=>request('payments/'+safe(id,'pay')),orderPayments:id=>request('orders/'+safe(id,'order')+'/payments'),refund:id=>request('refunds/'+safe(id,'rfnd')),paymentRefunds:id=>request('payments/'+safe(id,'pay')+'/refunds')};
}
