import {PaymentRecovery} from '../components/PaymentRecovery';
import React,{useEffect,useState} from 'react';
import {HAVIKAR_PRODUCTS} from '../lib/content';
import {api} from '../lib/api';
import {launchRazorpayCheckout} from '../lib/razorpay';
const rupees=(amount:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(amount/100);
export function SecureGiftsPage({navigate}:{navigate:(path:string)=>void}){
 const [user,setUser]=useState<any>(null),[loading,setLoading]=useState(true),[cart,setCart]=useState<Record<string,number>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[version,setVersion]=useState(0);
 const [form,setForm]=useState({recipientName:'',giftMessage:'',deliveryAddress:'',city:'',pincode:'',customerEmail:'',boxPackaging:false});
 useEffect(()=>{let live=true;api('/session').then(r=>{if(live)setUser(r.user);}).catch(e=>{if(live&&e.status!==401)setError(e.message);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[]);
 return <section className="max-w-6xl mx-auto px-5 py-10 space-y-8"><div><p className="text-xs uppercase text-gold-dark tracking-widest">Mantrakshata gifts</p><h1 className="font-serif text-4xl">Sacred gifts, thoughtfully delivered</h1><p className="mt-3 text-sm">Choose your gifts and request a quote. We confirm stock, delivery coverage and the full price before payment. Shipping is handled manually through India Post.</p></div>
 {error&&<p role="alert" className="rounded-xl p-4 bg-red-50 text-red-800">{error}</p>}{notice&&<p role="status" className="rounded-xl p-4 bg-green-50 text-green-800">{notice}</p>}
 <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">{HAVIKAR_PRODUCTS.map(p=><article key={p.id} className="rounded-2xl border bg-white overflow-hidden"><img src={p.image} alt={p.name} loading="lazy" className="w-full h-44 object-cover"/><div className="p-4 space-y-2"><h2 className="font-serif text-xl">{p.name}</h2><p className="text-sm">{p.description}</p><p className="text-xs text-gold-dark">Price to be confirmed</p><label className="block text-sm">Quantity for {p.name}<input type="number" min={0} max={20} value={cart[p.id]||0} onChange={e=>setCart(c=>({...c,[p.id]:Math.max(0,Math.min(20,Math.floor(Number(e.target.value)||0)))}))} className="block border rounded-lg p-2 w-24 mt-1"/></label></div></article>)}</div>
 {loading?<p role="status">Checking sign-in…</p>:!user?<button className="bg-gold text-white rounded-xl p-3" onClick={()=>navigate('/portal')}>Sign in to request gifts</button>:!user.name?<button className="underline" onClick={()=>navigate('/portal')}>Complete your registration to request gifts</button>:<form className="max-w-3xl rounded-2xl border bg-white p-5 space-y-4" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');setNotice('');try{const items=Object.entries(cart).filter(([,quantity])=>quantity>0).map(([id,quantity])=>({id,quantity}));const r=await api('/gifts',{...form,items});setNotice('Gift request '+r.gift.id+' saved. We will confirm stock, shipping and the price before you pay.');setCart({});setVersion(v=>v+1);}catch(e:any){setError(e.message);}finally{setBusy(false);}}}><h2 className="font-serif text-2xl">Recipient and delivery details</h2><div className="grid sm:grid-cols-2 gap-4">{[['recipientName','Recipient name','text'],['customerEmail','Email (optional)','email'],['deliveryAddress','Full delivery address','text'],['city','City / town / village','text'],['pincode','Indian PIN code','text']].map(([key,label,type])=><label key={key} className="block text-sm">{label}<input required={key!=='customerEmail'} type={type} maxLength={key==='deliveryAddress'?1000:200} pattern={key==='pincode'?'[1-9][0-9]{5}':undefined} value={(form as any)[key]} onChange={e=>setForm(f=>({...f,[key]:e.target.value}))} className="block border rounded-xl p-3 w-full mt-1"/></label>)}</div><label className="block text-sm">Gift message (optional)<textarea maxLength={1000} value={form.giftMessage} onChange={e=>setForm(f=>({...f,giftMessage:e.target.value}))} className="border rounded-xl p-3 w-full block"/></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={form.boxPackaging} onChange={e=>setForm(f=>({...f,boxPackaging:e.target.checked}))}/>Request keepsake box packaging; charge included in the final quote.</label><p className="text-xs">Your verified mobile number +{user.phone} is used for this order. Payment will include the quoted shipping and packaging charges.</p><button disabled={busy} className="bg-gold text-white rounded-xl p-3 disabled:opacity-50">{busy?'Saving…':'Request gift quote'}</button></form>}
 {user&&<OrderManagement key={version} user={user}/>}<button className="underline" onClick={()=>navigate('/book')}>Looking for a ceremony? Plan a Vardhantotsava</button>
 </section>;
}
export function OrderManagement({user}:{user:any}){
 const [gifts,setGifts]=useState<any[]>([]),[payments,setPayments]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const refresh=async()=>{setGifts((await api('/gifts')).gifts);if(user.role==='admin')setPayments((await api('/admin/payments')).payments);};
 useEffect(()=>{let live=true;api('/gifts').then(r=>{if(live)setGifts(r.gifts);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[user.phone]);
 const act=async(work:()=>Promise<any>)=>{if(busy)return;setBusy(true);setError('');try{await work();await refresh();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 return <div className="space-y-4"><h2 className="font-serif text-2xl">{user.role==='admin'?'Gift fulfilment':'Your gift orders'}</h2>{error&&<p role="alert" className="text-red-800">{error}</p>}<button disabled={busy} className="underline text-sm" onClick={()=>void act(async()=>{})}>Refresh gift and payment status</button>{!gifts.length&&<p className="text-sm">No gift orders yet.</p>}{gifts.map(g=><article key={g.id} className="border rounded-2xl bg-white p-5 space-y-2"><h3 className="font-serif text-xl">Gift for {g.recipientName}</h3><p className="text-xs break-all">{g.id} · {g.status}</p><p className="text-sm">{g.items.map((i:any)=>i.name+' × '+i.quantity).join(', ')}</p><p className="text-sm">{g.deliveryAddress}, {g.city} {g.pincode}</p>{g.giftMessage&&<p className="text-sm">Message: {g.giftMessage}</p>}<p className="text-sm">{g.amount?`Total ${rupees(g.amount)} · shipping ${rupees(g.shippingAmount||0)} · packaging ${rupees(g.boxAmount||0)}`:'Final price and shipping awaiting confirmation'}</p>{g.stockApproved&&g.status==='requested'&&<button disabled={busy} className="bg-gold text-white rounded-xl p-3" onClick={()=>{setBusy(true);setError('');void launchRazorpayCheckout({kind:'gift',bookingId:g.id,amount:0,packageName:'Sacred gift order',customerName:user.name,customerPhone:user.phone,onSuccess:()=>{setBusy(false);void act(async()=>{});},onFailure:e=>{setError(e);setBusy(false);},onDismiss:()=>setBusy(false)});}}>Pay full quoted amount</button>}{g.trackingNumber&&<p className="text-sm">India Post: <strong>{g.trackingNumber}</strong> · <a href="https://www.indiapost.gov.in/" target="_blank" rel="noreferrer" className="underline">Track on India Post</a></p>}{user.role==='admin'&&<GiftActions gift={g} busy={busy} act={act}/>}</article>)}
 {user.role==='admin'&&<div className="space-y-2"><h3 className="font-serif text-xl">Payment reconciliation</h3><p className="text-xs">Initiate approved refunds manually in the payment gateway dashboard. This page records provider-confirmed outcomes.</p><button disabled={busy} className="underline" onClick={()=>void act(()=>api('/admin/payments/reconcile',{}))}>Check pending payments</button>{payments.map(p=><div key={p.id}><p className="text-xs border-b py-2 break-all">{p.target} · {p.state} · {rupees(p.amount)} · {p.payment||'No captured payment'}{p.error?' · '+p.error:''}{p.refunds?.map((r:any)=>` · Refund ${r.id}: ${r.status} ${rupees(r.amount)}`)}</p><PaymentRecovery record={p} busy={busy} act={act}/></div>)}</div>}
 </div>;
}
function GiftActions({gift:g,busy,act}:{gift:any;busy:boolean;act:(work:()=>Promise<any>)=>Promise<void>}){const [tracking,setTracking]=useState('');return <div className="flex flex-wrap gap-3 border-t pt-3">{g.status==='requested'&&!g.stockApproved&&<button disabled={busy} className="underline" onClick={()=>void act(()=>api('/gifts/'+g.id+'/approve',{}))}>Approve stock, delivery coverage and final quote</button>}{g.status==='paid'&&<button disabled={busy} className="underline" onClick={()=>void act(()=>api('/gifts/'+g.id+'/fulfil',{action:'pack'}))}>Mark packed</button>}{['paid','packed'].includes(g.status)&&<form className="flex flex-wrap gap-2" onSubmit={e=>{e.preventDefault();void act(()=>api('/gifts/'+g.id+'/fulfil',{action:'ship',trackingNumber:tracking}));}}><label className="text-sm">India Post consignment number<input aria-label={'India Post number for '+g.id} required pattern="[A-Za-z]{2}[0-9]{9}[Ii][Nn]" value={tracking} onChange={e=>setTracking(e.target.value)} className="block border p-2 rounded-lg"/></label><button disabled={busy} className="underline">Save shipment</button></form>}{g.status==='shipped'&&<button disabled={busy} className="underline" onClick={()=>void act(()=>api('/gifts/'+g.id+'/fulfil',{action:'deliver'}))}>Confirm delivered</button>}{g.trackingNumber&&<a className="underline" target="_blank" rel="noreferrer" href={'https://wa.me/'+g.customerPhone+'?text='+encodeURIComponent(`Namaskara ${g.customerName}, your Mantrakshata gift order ${g.id} for ${g.recipientName} has been shipped through India Post. Tracking number: ${g.trackingNumber}. Track at https://www.indiapost.gov.in/. Thank you.`)}>Open WhatsApp shipment update</a>}</div>;}
