import {OrderManagement} from './SecureGiftsPage';
import {launchRazorpayCheckout} from '../lib/razorpay';
import React,{useEffect,useState} from 'react';
import {BirthplaceInput} from '../components/BirthplaceInput';
import {api} from '../lib/api';
import {ManualVedicFields,emptyVedic} from '../components/ManualVedicFields';
import {PACKAGES} from '../lib/content';

export function SecurePortalPage({mode='dashboard',navigate}:{mode?:'book'|'gift'|'dashboard'|'admin';navigate:(p:string)=>void}){
 const [user,setUser]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [phone,setPhone]=useState(''),[challenge,setChallenge]=useState(''),[code,setCode]=useState(''),[name,setName]=useState(''),[marketing,setMarketing]=useState(false);
 const [bookings,setBookings]=useState<any[]>([]),[jobs,setJobs]=useState<any[]>([]),[vedic,setVedic]=useState(emptyVedic),[manual,setManual]=useState(false);
 const [form,setForm]=useState({name:'',dob:'',relationship:'',birthPlace:'',birthTime:'',celebrationDate:'',time:'09:00',address:'',mapsLink:'',pincode:'',email:'',packageId:PACKAGES[0].id});
 const update=(key:string,value:string)=>setForm(f=>({...f,[key]:value}));
 const act=async(task:()=>Promise<void>)=>{if(busy)return;setBusy(true);setError('');setNotice('');try{await task();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 const refresh=async()=>{const result=await api('/bookings');setBookings(result.bookings);};
 useEffect(()=>{let live=true;api('/session').then(async r=>{if(!live)return;setUser(r.user);window.dispatchEvent(new Event('user_profile_updated'));setName(r.user.name||'');const b=await api('/bookings');if(live)setBookings(b.bookings);}).catch(e=>{if(live&&e.status!==401)setError(e.message);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[]);
 const field=(label:string,key:keyof typeof form,type='text',required=true)=><label className="block text-sm space-y-1"><span>{label}</span><input className="w-full rounded-xl border border-gold/30 bg-white p-3" type={type} required={required} value={form[key]} onChange={e=>update(key,e.target.value)} max={key==='dob'?new Date().toISOString().slice(0,10):undefined}/></label>;
 if(loading)return <section className="p-12 text-center" role="status">Checking your secure session…</section>;
 return <section className="max-w-4xl mx-auto px-5 py-10 space-y-6"><div><p className="text-xs uppercase tracking-widest text-gold-dark">Mantrakshata</p><h1 className="font-serif text-3xl">{!user?'Sign in with WhatsApp':mode==='gift'?'Gift a Vardhantotsava':mode==='book'?'Request your Vardhantotsava':mode==='admin'?'Ceremony operations':'Your celebrations'}</h1></div>{error&&<p role="alert" className="p-4 rounded-xl bg-red-50 text-red-800">{error}</p>}{notice&&<p role="status" className="p-4 bg-green-50 text-green-800 rounded-xl">{notice}</p>}
 {!user?<form className="max-w-md space-y-4" onSubmit={e=>{e.preventDefault();void act(async()=>{if(challenge){const r=await api('/auth/verify',{challengeId:challenge,code});setUser(r.user);setName(r.user.name||'');setCode('');setChallenge('');await refresh();}else{const r=await api('/auth/request',{phone});setChallenge(r.challengeId);setNotice('A verification code was sent to your WhatsApp. It expires in 10 minutes.');}});}}><label className="block text-sm">Mobile number<input aria-label="Mobile number" type="tel" autoComplete="tel" required disabled={!!challenge||busy} value={phone} onChange={e=>setPhone(e.target.value)} className="block w-full border p-3 rounded-xl mt-1"/></label>{challenge&&<label className="block text-sm">Verification code<input aria-label="Verification code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} className="block w-full border p-3 rounded-xl mt-1"/></label>}<p className="text-xs text-charcoal/70">By requesting a code, you agree to receive a WhatsApp verification message for this sign-in.</p><button disabled={busy} className="bg-gold text-white rounded-xl px-5 py-3 disabled:opacity-50">{busy?'Please wait…':challenge?'Verify and sign in':'Send WhatsApp code'}</button>{challenge&&<button type="button" disabled={busy} className="ml-4 underline" onClick={()=>{setChallenge('');setCode('');setNotice('Wait at least one minute between code requests.');}}>Change number / request again</button>}</form>:<>
 <div className="flex gap-4 flex-wrap text-sm"><span>Signed in: +{user.phone}</span><button className="underline" disabled={busy} onClick={()=>void act(async()=>{await api('/auth/logout',{});setUser(null);window.dispatchEvent(new Event('user_profile_updated'));setBookings([]);setJobs([]);localStorage.removeItem('mantrakshata_user_profile');})}>Sign out</button><button className="underline" onClick={()=>navigate('/dashboard')}>My bookings</button><button className="underline" onClick={()=>navigate('/book')}>New ceremony</button>{user.role==='admin'&&<button className="underline" onClick={()=>navigate('/admin')}>Operations</button>}</div>
 {!user.name?<form className="max-w-md space-y-4" onSubmit={e=>{e.preventDefault();void act(async()=>{const r=await api('/profile',{name,marketing});setUser(r.user);setNotice('Thank you for registering with Mantrakshata.');});}}><label className="block">Your full name<input required maxLength={120} value={name} onChange={e=>setName(e.target.value)} className="block w-full border p-3 rounded-xl"/></label><label className="flex items-start gap-3 text-sm"><input type="checkbox" checked={marketing} onChange={e=>setMarketing(e.target.checked)}/>Send me the welcome catalogue and next-day feedback request on WhatsApp (optional).</label><button disabled={busy} className="bg-gold text-white rounded-xl p-3">Complete registration</button></form>:(mode==='book'||mode==='gift')?<form className="space-y-5" onSubmit={e=>{e.preventDefault();void act(async()=>{const pkg=PACKAGES.find(p=>p.id===form.packageId)!;await api('/bookings',{...form,...vedic,occasion:mode==='gift'?'Gifted Vardhantotsava':'Vardhantotsava',packageName:pkg.name,timeSlot:form.time,ceremonyStart:form.celebrationDate+'T'+form.time+':00+05:30'});await refresh();setNotice('Request saved securely. Your ceremony is not confirmed until availability and full payment are verified.');navigate('/dashboard');});}}><p className="text-sm text-charcoal/70">Bengaluru home ceremonies · at least 48 hours’ notice · prices require confirmation. Saving this request does not charge you.</p><div className="grid sm:grid-cols-2 gap-4">{field('Celebrant full name','name')}{field('Date of birth','dob','date')}{field('Birth time (optional)','birthTime','time',false)}<label className="block text-sm">Place of birth<BirthplaceInput value={form.birthPlace} onChange={v=>update('birthPlace',v)} className="w-full rounded-xl border p-3"/></label></div>{mode==='gift'&&field('Relationship to the celebrant (optional)','relationship','text',false)}<ManualVedicFields enabled={manual} onToggle={setManual} value={vedic} onChange={setVedic}/><div className="grid sm:grid-cols-2 gap-4">{field('Ceremony date','celebrationDate','date')}{field('Ceremony start time (IST)','time','time')}{field('Complete street address','address')}{field('Google Maps link (compulsory)','mapsLink','url')}{field('Bengaluru PIN code','pincode')}{field('Email (optional)','email','email',false)}<label className="block text-sm">Package<select value={form.packageId} onChange={e=>update('packageId',e.target.value)} className="block w-full p-3 border rounded-xl">{PACKAGES.map(p=><option key={p.id} value={p.id}>{p.name} — price to be confirmed</option>)}</select></label></div><button disabled={busy} className="bg-gold text-white rounded-xl px-6 py-3 disabled:opacity-50">{busy?'Saving…':'Save ceremony request'}</button></form>:mode==='admin'&&user.role!=='admin'?<p role="alert">Your account does not have staff access.</p>:<>
 <div className="space-y-4">{bookings.length===0&&<p>No ceremony requests yet.</p>}{bookings.filter(b=>{const selected=new URLSearchParams(location.search).get('bookingId');return !selected||b.id===selected;}).map(b=><article className="rounded-2xl border border-gold/30 bg-white p-5 space-y-2" key={b.id}><h2 className="font-serif text-xl">{b.name}</h2><p className="text-xs break-all">{b.id} · {b.status}</p><p>{new Date(b.ceremonyStart).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST</p><p>{b.packageName} · {b.address}, {b.pincode}</p><p>{b.pandit?`Pandit: ${b.pandit.name} · ${b.pandit.phone} · Arrival ${b.pandit.arrival}`:'Pandit assignment pending'}</p>{b.status==='requested'&&<p className="text-sm">{b.availabilityApproved?'Approved quote: ₹'+(b.amount/100).toLocaleString('en-IN'):'Awaiting availability and final price approval'}</p>}{b.status==='requested'&&b.availabilityApproved&&b.amount&&<button disabled={busy} className="bg-gold text-white rounded-xl p-3" onClick={()=>{setBusy(true);setError('');void launchRazorpayCheckout({bookingId:b.id,amount:0,packageName:b.packageName,customerName:user.name,customerPhone:user.phone,onSuccess:()=>{setBusy(false);void refresh().catch(e=>setError(e.message));setNotice('Payment verified. Your booking is confirmed.');},onFailure:e=>{setBusy(false);setError(e);},onDismiss:()=>setBusy(false)});}}>Pay full quoted amount</button>}{mode==='admin'&&user.role==='admin'&&<StaffActions booking={b} busy={busy} run={task=>void act(async()=>{await task();await refresh();})}/>}</article>)}</div>{new URLSearchParams(location.search).has('bookingId')&&!bookings.some(b=>b.id===new URLSearchParams(location.search).get('bookingId'))&&<p role="alert">Booking not found or not accessible to your account.</p>}
 <OrderManagement user={user}/>{mode==='admin'&&user.role==='admin'&&<div className="space-y-3"><button className="underline" onClick={()=>void act(async()=>setJobs((await api('/admin/jobs')).jobs))}>Refresh reminder and delivery queue</button>{jobs.map(j=><p key={j.id} className="text-xs break-all border-b py-2">{j.kind} · {j.booking||'Registration'} · {j.delivery||j.state} · {new Date(j.due).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})}{j.error?' · '+j.error:''}{j.state==='failed'&&<button className="ml-3 underline" onClick={()=>void act(async()=>{await api('/admin/jobs/'+encodeURIComponent(j.id)+'/retry',{});setJobs((await api('/admin/jobs')).jobs);})}>Retry failed message</button>}</p>)}</div>}
 </>}
 </>}
 </section>;
}
function StaffActions({booking:b,busy,run}:{booking:any;busy:boolean;run:(task:()=>Promise<void>)=>void}){const [action,setAction]=useState('assign'),[name,setName]=useState(''),[phone,setPhone]=useState(''),[arrival,setArrival]=useState(''),[date,setDate]=useState(''),[paymentId,setPayment]=useState('');return <form className="border-t pt-3 space-y-3" onSubmit={e=>{e.preventDefault();run(async()=>{await api(`/bookings/${b.id}/${action}`,{name,phone,arrival,paymentId,ceremonyStart:date?date+':00+05:30':undefined});});}}><label className="text-sm">Staff action<select className="border rounded-lg p-2 ml-2" value={action} onChange={e=>setAction(e.target.value)}>{['approve','assign','confirm','reschedule','cancel','complete'].map(a=><option key={a}>{a}</option>)}</select></label>{action==='approve'&&<label className="flex gap-2 text-sm"><input type="checkbox" required/>I have checked ceremony availability and the final server price.</label>}{action==='assign'&&<div className="flex flex-wrap gap-2"><input aria-label="Pandit name" placeholder="Pandit name" required value={name} onChange={e=>setName(e.target.value)} className="border p-2 rounded-lg"/><input aria-label="Pandit phone" placeholder="Pandit WhatsApp number" required value={phone} onChange={e=>setPhone(e.target.value)} className="border p-2 rounded-lg"/><input aria-label="Expected arrival" placeholder="Expected arrival (IST)" required value={arrival} onChange={e=>setArrival(e.target.value)} className="border p-2 rounded-lg"/></div>}{action==='reschedule'&&<input aria-label="New ceremony date and time" type="datetime-local" required value={date} onChange={e=>setDate(e.target.value)} className="border p-2 rounded-lg"/>}{action==='confirm'&&<label className="block text-sm">Captured Razorpay payment ID<input required value={paymentId} onChange={e=>setPayment(e.target.value)} className="border p-2 rounded-lg block"/><span className="text-xs">Server checks amount, capture and booking reference. Availability must also be agreed.</span></label>}{['cancel','complete'].includes(action)&&<label className="flex gap-2 text-sm"><input type="checkbox" required key={action}/>I confirm this {action==='cancel'?'cancellation':'completed ceremony'}.</label>}<button disabled={busy} className="bg-gold text-white px-4 py-2 rounded-lg">Apply action</button></form>;}
