import assert from 'node:assert/strict';
export async function verifyCommerce({context,page,browser,root,service,sent,result}){
 const staff=await browser.newContext({viewport:{width:1440,height:900}}),staffPage=await staff.newPage();staffPage.on('pageerror',e=>result.browserErrors.push('Staff: '+e.message));
 try{const headers={origin:root};const challenge=await(await staff.request.post(root+'/api/auth/request',{headers,data:{phone:'9876543210'}})).json();const login=await staff.request.post(root+'/api/auth/verify',{headers,data:{challengeId:challenge.challengeId,code:sent.at(-1).args[0]}});assert.equal(login.status(),200);await staff.request.post(root+'/api/profile',{headers,data:{name:'Audit Coordinator'}});
 const booking=service.db.prepare('SELECT id FROM bookings').get();await staffPage.goto(root+'/admin');const bookingCard=staffPage.locator('article').filter({hasText:booking.id});await bookingCard.locator('select').selectOption('approve');await bookingCard.getByRole('checkbox').check();await bookingCard.getByRole('button',{name:'Apply action',exact:true}).click();await page.waitForFunction(()=>true);for(let i=0;i<20&&!JSON.parse(service.db.prepare('SELECT data FROM bookings WHERE id=?').get(booking.id).data).availabilityApproved;i++)await page.waitForTimeout(100);assert.equal(JSON.parse(service.db.prepare('SELECT data FROM bookings WHERE id=?').get(booking.id).data).availabilityApproved,true);
 await page.reload();await page.getByRole('button',{name:'Pay full quoted amount',exact:true}).click();await page.getByText(booking.id+' · confirmed',{exact:true}).waitFor();assert.equal(service.db.prepare('SELECT status FROM bookings WHERE id=?').get(booking.id).status,'confirmed');result.checks.push('Staff availability approval → mock Razorpay Checkout → verified booking confirmation');
 await page.goto(root+'/gifts');await page.getByRole('spinbutton',{name:'Quantity for Sandalwood Bracelet (Chandana Bandha)',exact:true}).fill('2');await page.getByLabel('Recipient name',{exact:true}).fill('Gift Recipient');await page.getByLabel('Full delivery address',{exact:true}).fill('22 Audit Delivery Road');await page.getByLabel('City / town / village',{exact:true}).fill('Mumbai');await page.getByLabel('Indian PIN code',{exact:true}).fill('400001');await page.getByRole('button',{name:'Request gift quote',exact:true}).click();await page.getByRole('heading',{name:'Gift for Gift Recipient',exact:true}).waitFor();const gift=service.db.prepare('SELECT id FROM gifts').get();
 await staffPage.reload();let giftCard=staffPage.locator('article').filter({hasText:gift.id});await giftCard.getByRole('button',{name:'Approve stock, delivery coverage and final quote',exact:true}).click();for(let i=0;i<20&&!JSON.parse(service.db.prepare('SELECT data FROM gifts WHERE id=?').get(gift.id).data).stockApproved;i++)await page.waitForTimeout(100);assert.equal(JSON.parse(service.db.prepare('SELECT data FROM gifts WHERE id=?').get(gift.id).data).stockApproved,true);
 await page.reload();await page.getByRole('button',{name:'Pay full quoted amount',exact:true}).click();await page.getByText(gift.id+' · paid',{exact:true}).waitFor();await staffPage.reload();giftCard=staffPage.locator('article').filter({hasText:gift.id});await giftCard.getByRole('button',{name:'Mark packed',exact:true}).click();await giftCard.getByText(gift.id+' · packed',{exact:true}).waitFor();await giftCard.getByLabel('India Post number for '+gift.id).fill('EA123456789IN');await giftCard.getByRole('button',{name:'Save shipment',exact:true}).click();await giftCard.getByText(gift.id+' · shipped',{exact:true}).waitFor();await page.reload();await page.getByText('EA123456789IN',{exact:true}).waitFor();assert.ok(await giftCard.getByRole('link',{name:'Open WhatsApp shipment update',exact:true}).getAttribute('href'));result.checks.push('Gift quote → staff approval → mock checkout → packed → India Post shipment visible to customer');await page.screenshot({path:'docs/diagnostic-gift-order.png',fullPage:true});await page.goto(root+'/dashboard');
 }finally{await staff.close();}
}
